### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-france#115]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_bank_statement_import_fr_cfonb
- [ ] account_banking_fr_lcr
- [ ] l10n_fr_account_fiscal_position_rule
- [ ] l10n_fr_account_tax_unece
- [ ] l10n_fr_base_location_geonames_import
- [ ] l10n_fr_business_document_import
- [ ] l10n_fr_department
- [ ] l10n_fr_department_delivery
- [ ] l10n_fr_department_oversea
- [ ] l10n_fr_intrastat_product
- [ ] l10n_fr_intrastat_service
- [ ] l10n_fr_naf_ape
- [ ] l10n_fr_siret
- [ ] l10n_fr_state

**Comment by fmdl** [comment]
MIG l10n_siret : https://github.com/OCA/l10n-france/pull/128

**Comment by njeudy** [comment]
@pedrobaeza : #129 

And can you add me as editor for this issue ? that I can change comment and add working PR ?

**Comment by pedrobaeza** [comment]
I'm afraid that's not possible. GitHub doesn't have that option. You need to be owner of the repository for that.

**Comment by njeudy** [comment]
it was to help you in this task :) no problem 

@pedrobaeza some module from V10 are missing in the list of module to migrate. I think readme has not be updateted on the repository ?

**Comment by pedrobaeza** [comment]
Any way, normally I let this specific localization issues to be maintained by localization PSC, for avoiding errors by the unknowledge of the peculiarities of each country.

**Comment by njeudy** [comment]
@pedrobaeza one more ;) : l10n_fr_department (~~#130~~) #131 sorry i delete the branch :(
who is in localization PSC ? @alexis-via ?

**Comment by pedrobaeza** [comment]
And @sebastienbeau @legalsylvain @fclementic2c as well

**Comment by njeudy** [comment]
I will try to migrate all needed l10n_fr module to V11 to group review and time to review

**Comment by ghost** [comment]
@njeudy @pedrobaeza can I help you to migrate l10n_fr_department_oversea?

**Comment by njeudy** [comment]
@danhvophuong yes of course :) create a PR and comment here with the reference !

**Comment by ghost** [comment]
ok, I will help to migrate "l10n_fr_department_oversea". It seems that the list of migrated module is not upgraded correctly

**Comment by njeudy** [comment]
@alexis-via @sebastienbeau @legalsylvain @fclementic2c @pedrobaeza can I have access to update issue, triage and so on this repos ?

**Comment by ghost** [comment]
MIG l10n_fr_department_oversea: https://github.com/OCA/l10n-france/pull/136

**Comment by fmdl** [comment]
MIG of account bank statement import fr cfonb: https://github.com/OCA/l10n-france/pull/138
