### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-france#373]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_balance_ebp_csv_export - By @alexis-via - #419
- [x] account_banking_fr_lcr - By @alexis-via - #403
- [x] account_statement_import_fr_cfonb - By @florian-dacosta - #397
- [x] l10n_fr_account_invoice_facturx - By @alexis-via - #408
- [x] l10n_fr_account_invoice_import_facturx - By @alexis-via - #430
- [x] l10n_fr_account_invoice_import_simple_pdf - By @alexis-via - #430
- [x] l10n_fr_account_tax_unece - By @alexis-via - #400
- [ ] l10n_fr_account_vat_return - By @alexis-via - #440
- [ ] l10n_fr_account_vat_return_teledec - By @alexis-via - #440
- [x] l10n_fr_business_document_import - By @alexis-via - #430
- [x] l10n_fr_chorus_account - By @alexis-via - #408
- [x] l10n_fr_chorus_facturx - By @alexis-via - #408
- [x] l10n_fr_chorus_sale - By @alexis-via - #408
- [x] l10n_fr_cog - By @alexis-via - #437
- [x] l10n_fr_das2 - By @alexis-via - #437
- [x] l10n_fr_department - By @alexis-via - #399
- [x] l10n_fr_department_oversea - By @alexis-via - #399
- [x] l10n_fr_ecotaxe - By @mourad-ehm - #448 MOVING to oca/account-fiscal-rule (see https://github.com/OCA/l10n-france/issues/483) 
- [ ] l10n_fr_ecotaxe_product - By @mourad-ehm - #450 MOVING to oca/account-fiscal-rule (see above)
- [ ] l10n_fr_ecotaxe_sale - By @mourad-ehm - #449 MOVING to oca/account-fiscal-rule (see above)
- [ ] l10n_fr_fec_oca - By @juliette-blanc - #405
- [x] l10n_fr_hr_check_ssnid - By @syera94 - #382
- [x] l10n_fr_intrastat_product - By @alexis-via - #413
- [x] l10n_fr_intrastat_service - By @alexis-via - #412
- [x] l10n_fr_mis_reports - By @alexis-via - #444
- [x] l10n_fr_oca - By @alexis-via - #423
- [x] l10n_fr_siret - By @alexis-via - #391
- [x] l10n_fr_siret_lookup - By @alexis-via - #392
- [x] l10n_fr_state - By @alexis-via - #398

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by linkweaver** [comment]
Hi,

I tried to migrate LCR module to 16.0 but I have this error below : 

`odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/account_payment_mode/views/account_payment_mode.xml:3
Error while validating view near:

<form string="Payment Mode" __validate__="1">
                <sheet>
                    <widget name="web_ribbon" title="Archived" bg_color="bg-danger" attrs="{'invisible': [('active', '=', True)]}"/>

Field 'company_id' used in domain of field 'variable_journal_ids' ([('company_id', '=', company_id), ('type', 'in', ('bank', 'cash'))]) is restricted to the group(s) base.group_multi_company.

View error context:
{'file': '/home/odoo/src/user/account_payment_mode/views/account_payment_mode.xml',
 'line': 1,
 'name': 'account.payment.mode.form',
 'view': ir.ui.view(858,),
 'view.model': 'account.payment.mode',
 'view.parent': ir.ui.view(),
 'xmlid': 'account_payment_mode_form'}
`

**Comment by alexis-via** [comment]
@linkweaver before porting the LCR module, make sure ALL the underlying modules are ported to v16!

**Comment by alexis-via** [comment]
Idea for DEB/DES: combine the generation of the XML export with the draft2done button. That way, users will not forget to set the declaration to done and, we make sure that, when the XML is generated, the declaration is not modified afterwards.
We should also rename DEB to EMEBI.

**Comment by alexis-via** [comment]
l10n_fr_department: we plan to rename the field department_id on res.partner, cf 
https://github.com/OCA/l10n-france/issues/384

**Comment by rafaelbn** [comment]
Hello @alexis-via ,

Are you working in any of this modules? Could we install as PR?

- [ ] l10n_fr_account_vat_return: https://github.com/OCA/l10n-france/pull/440
        "depends":
- [x] - l10n_fr (Odoo SA)
     - [ ] l10n_fr_oca: https://github.com/OCA/l10n-france/pull/423
        - [x] https://github.com/OCA/community-data-files/tree/16.0/base_unece
        - [x] https://github.com/OCA/community-data-files/tree/16.0/account_tax_unece
     **(Is this really needed? something to take care about?)**
     - [x] intrastat_base: https://github.com/OCA/intrastat-extrastat/tree/16.0/intrastat_base
     **(For a **100% service** company this is really needed?=**
     -  [x] onchange_helper: https://github.com/OCA/server-tools/tree/16.0/onchange_helper
        Note: Depends in Intrastat is not needed for every services companies
- [ ] l10n_fr_account_vat_return_teledec: https://github.com/OCA/l10n-france/pull/440
        "depends": ["l10n_fr_account_vat_return"],
- [ ] l10n_fr_fec_oca: https://github.com/OCA/l10n-france/pull/405
        "depends": ["l10n_fr", "account", "date_range"],
- [x] l10n_fr_mis_reports: https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_mis_reports
- [x] l10n_fr_siret: https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_siret
- [x] l10n_fr_siret_lookup: https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_siret_lookup

Thank you!
Regards

**Comment by Thatoo** [comment]
Hello,
[l10n_fr_chorus_account is on version 16 on the odoo app store](https://apps.odoo.com/apps/modules/16.0/l10n_fr_chorus_account/) but it requires  l10n_fr_chorus_facturx for what I understand which is not in version 16 on the odoo app store but only [on version 15](https://apps.odoo.com/apps/modules/15.0/l10n_fr_chorus_facturx/).

l10n_fr_chorus_sale is also available on v 16 but it requires  l10n_fr_chorus_account and thus l10n_fr_chorus_facturx .
