### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-france#42]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] l10n_fr_base_location_geonames_import
- [ ] l10n_fr_naf_ape
- [ ] l10n_fr_siret
- [ ] l10n_fr_department
- [ ] account_bank_statement_import_fr_cfonb
- [ ] l10n_fr_department_delivery
- [ ] l10n_fr_state
- [ ] l10n_fr_fec
- [ ] l10n_fr_account_fiscal_position_rule
- [ ] account_banking_fr_lcr
- [ ] l10n_fr_tax_sale_ttc

**Comment by rafaelbn** [comment]
Dear @legalsylvain or any one who knows french localization like @alexis-via or @OCA/local-france-maintainers  :smile: 

I have to evaluate an Odoo database in v9, which is using 

- l10n_fr (Odoo SA)
- l10n_fr_fec (Akretion, OCA)
- l10n_fr_reports (Odoo SA

The customer, Spanish, ask us to migrate from v9 to v12.

My question is: is there any work done in OCA or anywhere?

Thanks in advance

My best

**Comment by alexis-via** [comment]
The modules you are listing above are not OCA modules:
- l10n_fr is from the official addons, so it's already ported to v12
- l10n_fr_fec has been moved from OCA to the official addons in v9, so it's also already available in v12
- I don't know this module l10n_fr_reports ; maybe it's from Odoo Enterprise

**Comment by rafaelbn** [comment]
Thank you @alexis-via ! So it look like we can migrate :smile:
