### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-france#85]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_bank_statement_import_fr_cfonb
- [ ] account_banking_fr_lcr
- [ ] l10n_fr_account_fiscal_position_rule
- [ ] l10n_fr_base_location_geonames_import
- [ ] l10n_fr_department
- [ ] l10n_fr_department_delivery
- [ ] l10n_fr_department_oversea
- [ ] l10n_fr_fec
- [ ] l10n_fr_naf_ape
- [ ] l10n_fr_siret
- [ ] l10n_fr_state
